id: IE3913F9D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T10:50:07+00:00'
last_modified: '2022-06-15T18:34:13.768253+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN7871
  title: དམ་པའི་ཆོས་མངོན་པ་ཀུན་ལས་བཏུས་པའི་རྒྱ་ཆེར་འགྲེལ་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    164F:
      image_group_id: I3CN7873
      title: Volume 1 of dam pa'i chos mngon pa kun las btus pa'i rgya cher 'grel
        ba legs bshad rgya mtsho/
      total_pages: 664
      order: 1
      base_file: 164F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
